### ISSUE TITLE
"import" in __init__.py causes error

### ISSUE THREAD

**Issue by limjcst** [Trim21/snakefood3#1]
I'm using __python3.7__.
After the package `ast` parses my `__init__.py`, it has a `ast.ImportFrom` node, with `node.module` is `None`.
This `None` makes [52nd line of `gen_deps.py`](https://github.com/Trim21/snakefood3/blob/7a66e5e5778820f4e404bd7521e0912f51b62709/snakefood3/gen_deps.py#L52) failed.
```
    module += '.' + node.module
TypeError: can only concatenate str (not "NoneType") to str
```

I change that line as `module += '.%s'  (node.module, )`, and the figure shows that `my_pkg` depends on `my_pkg.None`.
It may be fine to ignore `__init__.py`, or ensure `node.module` with a meaningful value.

**Comment by Trim21** [comment]
what module do you import in your __init__.py？

**Comment by Trim21** [comment]
What module do you import, a file or a package with `__init__.py`?
And what do you import. A var in package or a file/subpackage in a package?

**Comment by limjcst** [comment]
```
d:\Desktop
└─test
   ├─node.py
   └─__init__.py
```

```
# __init__.py
from . import node
```

```
# node.py
def test():
    print('Hello World')
```

And the output is,
```
d:\Desktop>python -m snakefood3 . test
Traceback (most recent call last):
  File "C:\python\python3.7\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
  File "C:\python\python3.7\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "C:\python\python3.7\lib\site-packages\snakefood3\__main__.py", line 3, in <module>
    main()
  File "C:\python\python3.7\lib\site-packages\snakefood3\gen_deps.py", line 127,
 in main
    python_path=python_path,
  File "C:\python\python3.7\lib\site-packages\snakefood3\gen_deps.py", line 52, in get_all_imports_of_file
    module += '.' + node.module
TypeError: can only concatenate str (not "NoneType") to str
```

It seems that `from . import a` is not taken into consideration.
Or maybe this is a terrible programming style :(

**Comment by Trim21** [comment]
It has nothing to do with code style, it a valid python3 syntax.

But i don't have enough time to fix it these days, I'll fix it later.
